apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: crossplane-sns-topic
  labels:
    marina.external-resource/aws: sns-external-topic
spec:
  forProvider:
    region: eu-central-1
    fifoTopic: true
  providerConfigRef:
    name: default