apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: crossplane-sns-topic-1
  labels:
    marina.external-resource/aws: sns-external-topic
spec:
  forProvider:
    displayName: crossplane-sns-topic-1
    region: eu-central-1
    fifoTopic: true
  providerConfigRef:
    name: default
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: crossplane-sns-fifo-topic-1
  labels:
    marina.external-resource/aws: sns-external-fifo-topic
spec:
  forProvider:
    displayName: crossplane-sns-fifo-topic-1
    region: eu-central-1
    fifoTopic: true
  providerConfigRef:
    name: default