apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: hpv-crossplane-test-buckt #"crossplane-test-{{randNumeric 24 | nospace -}}"
spec:
  forProvider:
    region: eu-central-1
  providerConfigRef:
    name: default
 # deletionPolicy: Orphan